# Generated by Django 4.1.7 on 2023-04-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
