# Generated by Django 4.1.7 on 2023-04-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_profile_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("company", "company account"),
                    ("candidate", "company account"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
