# Generated by Django 4.1.7 on 2023-04-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_profile_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.CharField(max_length=100),
        ),
    ]
