# Generated by Django 4.1.7 on 2023-04-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_profile_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="achievement",
            field=models.TextField(default="", max_length=400),
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_link",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AddField(
            model_name="profile",
            name="qualifications",
            field=models.TextField(default="", max_length=400),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.TextField(default="", max_length=400),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter_username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="whatsapp_number",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
