# Generated by Django 4.1.7 on 2023-04-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_profile_achievement_profile_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
    ]
