# Generated by Django 4.1.7 on 2023-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="whatsapp_number",
            field=models.CharField(default="", max_length=10),
        ),
    ]
