# Generated by Django 4.1.7 on 2023-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_profile_bio_alter_profile_whatsapp_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="courseOffer",
            fields=[
                (
                    "user",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("about", models.TextField(default="", max_length=500)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                (
                    "posting_photo",
                    models.ImageField(default="", upload_to="courseoffer"),
                ),
                ("link", models.CharField(blank=True, default="", max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name="interviewOffer",
            fields=[
                (
                    "user",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("about", models.TextField(default="", max_length=500)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                (
                    "posting_photo",
                    models.ImageField(default="", upload_to="interviewoffer"),
                ),
                ("link", models.CharField(blank=True, default="", max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name="jobOffer",
            fields=[
                (
                    "user",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("about", models.TextField(default="", max_length=500)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("posting_photo", models.ImageField(default="", upload_to="joboffers")),
                ("link", models.CharField(blank=True, default="", max_length=2500)),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="id",
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
