# Generated by Django 4.1.7 on 2023-04-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_courseoffer_interviewoffer_joboffer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseoffer",
            name="posting_photo",
            field=models.ImageField(upload_to="courseoffer"),
        ),
        migrations.AlterField(
            model_name="interviewoffer",
            name="posting_photo",
            field=models.ImageField(upload_to="interviewoffer"),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="posting_photo",
            field=models.ImageField(upload_to="joboffers"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(upload_to="profilepics/"),
        ),
    ]
