# Generated by Django 4.1.7 on 2023-04-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_courseoffer_posting_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseoffer",
            name="posting_photo",
            field=models.ImageField(upload_to="courseoffer/"),
        ),
        migrations.AlterField(
            model_name="interviewoffer",
            name="posting_photo",
            field=models.ImageField(upload_to="interviewoffer/"),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="posting_photo",
            field=models.ImageField(upload_to="joboffers/"),
        ),
    ]
