# Generated by Django 4.1.7 on 2023-04-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_courseoffer_posting_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseoffer",
            name="course_fee",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="job_salary",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="courseoffer",
            name="posting_photo",
            field=models.ImageField(upload_to="courseposts"),
        ),
        migrations.AlterField(
            model_name="interviewoffer",
            name="posting_photo",
            field=models.ImageField(upload_to="interviewposts"),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="posting_photo",
            field=models.ImageField(upload_to="jobposts"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(upload_to="profilephoto"),
        ),
    ]
